using System.ComponentModel;
using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.Connectors.OpenAI;


namespace CardMaker;

public class Tools
{
    private readonly Kernel kernel;
    private readonly string toolsList;
    // Generated by Copilot
    public Tools(string toolsList, Kernel kernel)
    {
        this.kernel = kernel;
        this.toolsList = toolsList;
    }

    [KernelFunction("save_cards")]
    [Description("Save the card suit to a local file.")]
    [return: Description("The full card suit in JSON format.")]
    public async Task<string> save_cards(string json_document, [Description("card suit name, such as hearts, clubs, spades, or diamonds")] string suit)
    {
        string filePath = $"{suit}_cards.json";
        await File.WriteAllTextAsync(filePath, json_document);
        return json_document;
    }

}

